### ISSUE TITLE
transform MVPress into a mu-plugin

### ISSUE THREAD

**Issue by dennschu** [ericmann/MVPress#2]
Hi there,

I'd like your solution very much because it enables a clean way of passing data into a template (e.g. `partial` method in [Middleman](http://middlemanapp.com/basics/templates/#toc_6)). 

I have read [your blogpost](http://eamann.com/tech/wordpress-mvc/) where you discussed and struggled about a proper way to add this *extension* to wordpress. 

What do you think about the use as mu-plugin?  

*Maybe there is a way to use a grunt task that concats your files... so that it possible to create the 'standard' plugin and mu-plugin from one codebase...*

**Comment by ericmann** [comment]
I've instead transformed the plugin into a Composer module. If this is something you want to use in a theme, merely `composer require ericmann/mvpress` from now on. The template and context objects are in the `\MVPress` namespace, as is a beefed-up version of `get_template_part()`.

For backwards compatibility, I've left the `mvpress_template_part()` function in the global namespace for now. However, I really want to push this kind of feature upstream to WordPress itself in the future, so please don't depend on that.

The point of explicitly namespacing the template object, context object, and `get_template_part()` replacement is so that this module is also _forwards_ compatible with whatever changes we introduce into WordPress itself down the line.

I do recognize the namespacing adds a PHP 5.3 requirement to the code, but I can live with that. I've also added unit testing (using [WP_Mock](https://github.com/10up/wp_mock) for now), which brings in a PHP 5.5 requirement for development (the tests depend on some >=5.5.9 modules). If/when I have time to produce a core patch, these tests will be ported to the WP Unit Test Framework.
